# tomcat
server:
  port: 8002
# spring boot admin
spring:
  application:
    name: kitty-backup
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# backup datasource
kitty:
  backup:
    datasource:
      host: 123.206.9.27
      userName: ugo
      password: 123456
      database: test